<a href="https://colab.research.google.com/github/shishir-py/deep-learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# what is tensor ?

**Tensor is the representation of higher dimensional datatype, Generally the tensor are the data type which are generally higher dimension and computational space**

# Creating the Tensor :

In [3]:
import tensorflow as tf
string=tf.Variable("this is variable", tf.string)
number=tf.Variable(432,tf.int64)
floats=tf.Variable(32.4,tf.float64)

In [6]:
print(string)
print(number)
print(floats)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is variable'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=432>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=32.4>


# Rank / Dimension of tensor

In [24]:
rank1_tensor=tf.Variable("this is string", tf.string)
rank2_tensor=tf.Variable(['string1','string2'],tf.string)
rank3_tensor=tf.Variable([['string1','string2'],['string3','string4']],tf.string)

In [25]:
print(rank1_tensor)
print(rank2_tensor)
print(rank3_tensor)



<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>
<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'string1', b'string2'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'string1', b'string2'],
       [b'string3', b'string4']], dtype=object)>


In [26]:
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor)) 
print(tf.rank(rank3_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


# Shape of Tensor ⚗

In [28]:
print(rank1_tensor.shape)
print(rank2_tensor.shape)
print(rank3_tensor.shape)


()
(2,)
(2, 2)


In [31]:
var=tf.Variable([[1,2],[3,4],[6,7]], tf.string)
var.shape

TensorShape([3, 2])

In [32]:
tf.rank(var)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Changing the shape of Tensor 

In [43]:
tf1=tf.ones([1,2,3])
tf2=tf.reshape(tf1,[1,3,2])
tf3=tf.reshape(tf2,[3,2,1])



In [44]:
print(tf1)
print(tf.rank(tf1))
print(tf2)
print(tf.rank(tf2))
print(tf3)
print(tf.rank(tf3))

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(1, 3, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


# Types of tensor


1.   variable
2.   constant
3.   placeholder
4.   sparse Tensor

**Except the Variable other tensor are immutable during execution**



# Eva;uating Tensor ⚖

**we need session to run the evaluation**

In [48]:
import tensorflow as tf

# Define a simple computation graph
x = tf.constant(2)
y = tf.constant(3)
z = tf.add(x, y)

# Evaluate the value of `z` using Eager Execution
result = z.numpy()

print(result) # Output: 5


5
